// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package server

import (
	"context"
	"gozerodemo/app/reply/internal/logic"
	"gozerodemo/app/reply/internal/svc"
	reply2 "gozerodemo/app/reply/reply"
)

type ReplyServer struct {
	svcCtx *svc.ServiceContext
	reply2.UnimplementedReplyServer
}

func NewReplyServer(svcCtx *svc.ServiceContext) *ReplyServer {
	return &ReplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServer) Comments(ctx context.Context, in *reply2.CommentsRequest) (*reply2.CommentsResponse, error) {
	l := logic.NewCommentsLogic(ctx, s.svcCtx)
	return l.Comments(in)
}
